language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2'

script: "mvn clean install"

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
